version: "3.3"

services:
  api:
    build: "./src"
    ports:
      - "8080:8080"
    volumes:
      - "./src:/app"
    working_dir: "/app"
    env_file:
      - ./env/db.env
    networks:
      - api-default

  mysql:
    build: "./mysql"
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/log:/var/log/mysql"
      - "mysql-data:/var/lib/mysql"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    env_file:
      - ./env/db.env
    networks:
      - api-default

networks:
  api-default:

volumes:
  mysql-data:
