version: "3.3"

services:
  web-dev:
    build: "./client"
    ports:
      - "3000:3000"
    volumes:
      - "./client:/usr/src/app"
      - /user/src/app/node_modules
    networks:
      - api-default

  api:
    build: "./api"
    ports:
      - "8080:8080"
    volumes:
      - "./api:/app"
    working_dir: "/app"
    env_file:
      - ./env/db.env
    networks:
      - api-default

  mysql:
    build: "./mysql"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/log:/var/log/mysql"
      - "mysql-data:/var/lib/mysql"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    env_file:
      - ./env/db.env
    networks:
      - api-default

networks:
  api-default:

volumes:
  mysql-data:
